"""message

Revision ID: 28648829bd3b
Revises: 8730b01a3e26
Create Date: 2025-11-21 19:56:58.234114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '28648829bd3b'
down_revision = '8730b01a3e26'
branch_labels = None
depends_on = None


def _replace_fk(batch_op, table_name, local_cols, remote_table, ondelete=None):
    """Drop/recreate a FK only when the current DB reports a name."""
    inspector = inspect(op.get_bind())
    matches = [
        fk["name"]
        for fk in inspector.get_foreign_keys(table_name)
        if fk.get("name") and fk.get("constrained_columns") == local_cols
    ]
    if not matches:
        return
    for name in matches:
        batch_op.drop_constraint(name, type_='foreignkey')
    batch_op.create_foreign_key(
        matches[0],
        remote_table,
        local_cols,
        ['id'],
        ondelete=ondelete,
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_user_slot'))
        _replace_fk(batch_op, 'member_meal', ['user_id'], 'user')

    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_member_meal_ingredient_meal_id'))
        _replace_fk(batch_op, 'member_meal_ingredient', ['food_id'], 'food')
        _replace_fk(batch_op, 'member_meal_ingredient', ['meal_id'], 'member_meal')

    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_member_slot'))
        _replace_fk(batch_op, 'trainer_meal', ['member_id'], 'user')
        _replace_fk(batch_op, 'trainer_meal', ['trainer_id'], 'user')

    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'))
        _replace_fk(batch_op, 'trainer_meal_ingredient', ['meal_id'], 'trainer_meal')
        _replace_fk(batch_op, 'trainer_meal_ingredient', ['food_id'], 'food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer_meal_ingredient', schema=None) as batch_op:
        _replace_fk(batch_op, 'trainer_meal_ingredient', ['food_id'], 'food', ondelete='CASCADE')
        _replace_fk(batch_op, 'trainer_meal_ingredient', ['meal_id'], 'trainer_meal', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trainer_meal', schema=None) as batch_op:
        _replace_fk(batch_op, 'trainer_meal', ['trainer_id'], 'user', ondelete='CASCADE')
        _replace_fk(batch_op, 'trainer_meal', ['member_id'], 'user', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trainer_meal_member_slot'), ['trainer_id', 'member_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('member_meal_ingredient', schema=None) as batch_op:
        _replace_fk(batch_op, 'member_meal_ingredient', ['meal_id'], 'member_meal', ondelete='CASCADE')
        _replace_fk(batch_op, 'member_meal_ingredient', ['food_id'], 'food', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_ingredient_meal_id'), ['meal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('member_meal', schema=None) as batch_op:
        _replace_fk(batch_op, 'member_meal', ['user_id'], 'user', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_member_meal_user_slot'), ['user_id', 'meal_slot'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
